const PDFDocument = require("pdfkit");

/**
 * Generate a professional candidate resume PDF buffer
 */
function generateResumePDF({ applicant, job, coverLetter, filename }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      const candidateName = applicant?.name || "Job Applicant";
      const candidateEmail = applicant?.email || "N/A";
      const candidatePhone = applicant?.phone || "N/A";
      const candidateLocation = applicant?.location || "N/A";
      const candidateEducation = applicant?.education || "N/A";
      const candidateSkills = applicant?.skills || "N/A";
      const jobTitle = job?.title || "Job Candidate";
      const companyName = job?.company || "HireFlow AI Partner";

      // Header Bar
      doc
        .rect(50, 45, 512, 5)
        .fill("#7c3aed");

      // Candidate Name & Title
      doc
        .fillColor("#1e1b4b")
        .fontSize(24)
        .font("Helvetica-Bold")
        .text(candidateName, 50, 65);

      doc
        .fillColor("#6d28d9")
        .fontSize(12)
        .font("Helvetica")
        .text(`Application for: ${jobTitle} at ${companyName}`, 50, 95);

      doc.moveDown(1);

      // Contact Information Box
      doc
        .rect(50, 120, 512, 45)
        .fillAndStroke("#f5f3ff", "#ddd6fe");

      doc
        .fillColor("#4c1d95")
        .fontSize(9)
        .font("Helvetica-Bold")
        .text("CONTACT & LOCATION", 60, 128);

      doc
        .fillColor("#334155")
        .fontSize(9)
        .font("Helvetica")
        .text(`Email: ${candidateEmail}  |  Phone: ${candidatePhone}  |  Location: ${candidateLocation}`, 60, 145);

      let currentY = 180;

      // Education & Skills Section
      doc
        .fillColor("#1e1b4b")
        .fontSize(13)
        .font("Helvetica-Bold")
        .text("Skills & Education", 50, currentY);

      doc
        .rect(50, currentY + 18, 512, 1)
        .fill("#e2e8f0");

      currentY += 28;

      doc
        .fillColor("#475569")
        .fontSize(10)
        .font("Helvetica-Bold")
        .text("Education: ", 50, currentY, { continued: true })
        .font("Helvetica")
        .text(candidateEducation);

      currentY += 20;

      doc
        .fillColor("#475569")
        .fontSize(10)
        .font("Helvetica-Bold")
        .text("Technical Skills: ", 50, currentY, { continued: true })
        .font("Helvetica")
        .text(candidateSkills);

      currentY += 35;

      // Cover Letter / Application Statement
      if (coverLetter) {
        doc
          .fillColor("#1e1b4b")
          .fontSize(13)
          .font("Helvetica-Bold")
          .text("Cover Letter & Candidate Statement", 50, currentY);

        doc
          .rect(50, currentY + 18, 512, 1)
          .fill("#e2e8f0");

        currentY += 28;

        doc
          .fillColor("#334155")
          .fontSize(10)
          .font("Helvetica")
          .text(coverLetter, 50, currentY, {
            width: 512,
            align: "justify",
            lineGap: 4,
          });
      }

      // Footer
      doc
        .fontSize(8)
        .fillColor("#94a3b8")
        .text(
          "Verified Candidate Application • Generated by HireFlow AI",
          50,
          730,
          { align: "center", width: 512 }
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = generateResumePDF;
